// SPDX-FileCopyrightText: 2026 The RIVER Authors
// SPDX-License-Identifier: MIT
//
// GENERATED by branding/render.sh from branding/logo/river-lockup-dark.svg: its viewBox, and
// where the community mark (its MARK_VIEWBOX, 512 units) sits in it. Never edit this file.
import QtQml

QtObject {
    readonly property real viewWidth: 820.52612
    readonly property real viewHeight: 197.68512
    readonly property real markScale: 0.410156
    readonly property real markX: -21.972069
    readonly property real markY: -5.3421034
}
