// SPDX-FileCopyrightText: 2026 The RIVER Authors
// SPDX-License-Identifier: MIT

package repocmd

import (
	"archive/tar"
	"bytes"
	"context"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"testing"
)

// --- fixtures ------------------------------------------------------------------------------

type fakePkg struct {
	name, ver, arch string
	files           map[string]string // path -> content
	dirs            []string
}

func (f fakePkg) fileName() string {
	return f.name + "-" + f.ver + "-" + f.arch + pkgSuffix
}

// tarBytes is the uncompressed package archive makepkg would write.
func (f fakePkg) tarBytes(t *testing.T) []byte {
	t.Helper()
	var b bytes.Buffer
	tw := tar.NewWriter(&b)
	add := func(name string, typ byte, body string) {
		h := &tar.Header{Name: name, Typeflag: typ, Mode: 0o644, Size: int64(len(body))}
		if typ == tar.TypeDir {
			h.Mode, h.Size = 0o755, 0
		}
		if err := tw.WriteHeader(h); err != nil {
			t.Fatal(err)
		}
		if typ != tar.TypeDir {
			if _, err := io.WriteString(tw, body); err != nil {
				t.Fatal(err)
			}
		}
	}
	add(".BUILDINFO", tar.TypeReg, "format = 2\n")
	add(".MTREE", tar.TypeReg, "")
	add(".PKGINFO", tar.TypeReg, fmt.Sprintf("# Generated by makepkg\npkgname = %s\npkgbase = %s\npkgver = %s\narch = %s\nsize = 1\n", f.name, f.name, f.ver, f.arch))
	for _, d := range f.dirs {
		add(d+"/", tar.TypeDir, "")
	}
	names := make([]string, 0, len(f.files))
	for n := range f.files {
		names = append(names, n)
	}
	slices.Sort(names)
	for _, n := range names {
		add(n, tar.TypeReg, f.files[n])
	}
	if err := tw.Close(); err != nil {
		t.Fatal(err)
	}
	return b.Bytes()
}

// read parses the fixture the way OpenPackage does, without zstd.
func (f fakePkg) read(t *testing.T, dir string) *Package {
	t.Helper()
	p, err := readPackage(bytes.NewReader(f.tarBytes(t)))
	if err != nil {
		t.Fatal(err)
	}
	p.File = f.fileName()
	p.Path = filepath.Join(dir, p.File)
	return p
}

func needTools(t *testing.T, names ...string) {
	t.Helper()
	for _, n := range names {
		if _, err := exec.LookPath(n); err != nil {
			t.Skipf("%s not installed: this test builds or reads real .pkg.tar.zst/signatures (the pure-Go tests cover the rules)", n)
		}
	}
}

// writeZst writes b to path compressed with the zstd tool.
func writeZst(t *testing.T, path string, b []byte) {
	t.Helper()
	cmd := exec.Command("zstd", "-q", "-f", "-o", path)
	cmd.Stdin = bytes.NewReader(b)
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("zstd: %v: %s", err, out)
	}
}

func (f fakePkg) write(t *testing.T, dir string) string {
	t.Helper()
	p := filepath.Join(dir, f.fileName())
	writeZst(t, p, f.tarBytes(t))
	return p
}

var (
	coreMarker = "usr/local/share/runink/core/PAYLOAD-NONE"
	baseCore   = fakePkg{name: "runink-core", ver: "2026.07-1", arch: "x86_64",
		dirs:  []string{"usr", "usr/local", "usr/local/share", "usr/local/share/runink", "usr/local/share/runink/core"},
		files: map[string]string{coreMarker: "This RIVER image was built without a downstream payload.\n"}}
	baseRuntime = fakePkg{name: "runink-runtime", ver: "2026.07-1", arch: "x86_64",
		dirs: []string{"usr", "usr/local", "usr/local/share", "usr/local/share/runink", "usr/local/share/runink/images"}}
	tayga = fakePkg{name: "runink-tayga", ver: "0.9.2-1", arch: "x86_64",
		files: map[string]string{"usr/bin/tayga": "\x7fELF"}}
)

func root(t *testing.T) string {
	t.Helper()
	r, err := filepath.Abs("../../..")
	if err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(r, "build/pkgbuilds")); err != nil {
		t.Skip("not in a river checkout")
	}
	return r
}

// --- the public guard ------------------------------------------------------------------------

func TestReadPackage(t *testing.T) {
	p := baseCore.read(t, t.TempDir())
	if p.Name != "runink-core" || p.Version != "2026.07-1" || p.Arch != "x86_64" {
		t.Fatalf("pkginfo: %+v", p)
	}
	if !slices.Equal(p.Files, []string{coreMarker}) {
		t.Fatalf("files %v (metadata must not count)", p.Files)
	}
	if _, err := readPackage(bytes.NewReader(nil)); err == nil {
		t.Fatal("an empty archive is not a package")
	}
}

func TestCheckPublic(t *testing.T) {
	with := func(f fakePkg, extra map[string]string) fakePkg {
		m := map[string]string{}
		for k, v := range f.files {
			m[k] = v
		}
		for k, v := range extra {
			if v == "<delete>" {
				delete(m, k)
				continue
			}
			m[k] = v
		}
		f.files = m
		return f
	}
	cases := []struct {
		name string
		pkg  fakePkg
		dir  string
		file string // override the file name
		want string // "" = public; else a fragment of the refusal
	}{
		{"base runink-core", baseCore, "", "", ""},
		{"base runink-runtime", baseRuntime, "", "", ""},
		{"runtime with the models manifest", with(baseRuntime, map[string]string{"usr/local/share/runink/models.manifest": "x"}), "", "", ""},
		{"a River package", tayga, "", "", ""},
		{"not on the allow-list", fakePkg{name: "acme-console", ver: "1-1", arch: "x86_64", files: map[string]string{"usr/bin/acme": "x"}}, "", "", "not on the public allow-list"},
		{"core with a deploy", with(baseCore, map[string]string{"usr/local/share/runink/core/deploy": "#!/bin/sh"}), "", "", "downstream payload file"},
		{"core with firstboot hooks", with(baseCore, map[string]string{"usr/local/lib/runink/firstboot.d/50-x": "x"}), "", "", "downstream payload file"},
		{"core without the marker", with(baseCore, map[string]string{coreMarker: "<delete>"}), "", "", "has no " + coreMarker},
		{"downstream core (full tree, no marker)", with(baseCore, map[string]string{coreMarker: "<delete>", "usr/local/share/runink/core/deploy": "x", "usr/local/share/runink/core/bin/core": "x"}), "", "", "2 downstream payload file(s)"},
		{"runtime with host binaries", with(baseRuntime, map[string]string{"usr/local/bin/objectd": "x"}), "", "", "downstream payload file"},
		{"runtime with an OCI image", with(baseRuntime, map[string]string{"usr/local/share/runink/images/app.tar": "x"}), "", "", "downstream payload file"},
		{"other package under a payload path", with(tayga, map[string]string{"usr/local/share/runink/core/deploy": "x"}), "", "", "downstream payload file"},
		{"private directory", tayga, "/build/state/localrepo-server-private", "", "private build directory"},
		{"server profile directory", tayga, "/build/state/localrepo-runink-server", "", "private build directory"},
		{"PRIVATE in capitals", tayga, "/x/PRIVATE/y", "", "private build directory"},
		{"file name not its .PKGINFO", tayga, "", "runink-tayga-9.9-1-x86_64" + pkgSuffix, "does not match its .PKGINFO"},
		{"a character GitHub rewrites", fakePkg{name: "runink-tayga", ver: "0.9.2+r1-1", arch: "x86_64"}, "", "", "GitHub would rewrite"},
		{"foreign arch", fakePkg{name: "runink-tayga", ver: "1-1", arch: "aarch64"}, "", "", "not x86_64"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			dir := c.dir
			if dir == "" {
				dir = "/build/localrepo-river"
			}
			p := c.pkg.read(t, dir)
			if c.file != "" {
				p.File = c.file
			}
			why := strings.Join(CheckPublic(p), "\n")
			if c.want == "" && why != "" {
				t.Fatalf("refused a public package: %s", why)
			}
			if c.want != "" && !strings.Contains(why, c.want) {
				t.Fatalf("want a refusal containing %q, got %q", c.want, why)
			}
		})
	}
}

// The allow-list is exactly what River's own PKGBUILDs build: a new PKGBUILD must be added to
// it on purpose, and a removed one taken off.
func TestPublicPackagesMatchPKGBUILDs(t *testing.T) {
	r := root(t)
	builds, _ := filepath.Glob(filepath.Join(r, "build/pkgbuilds/*/PKGBUILD"))
	if len(builds) == 0 {
		t.Fatal("no PKGBUILDs")
	}
	baseRE := regexp.MustCompile(`(?m)^pkgbase=(\S+)`)
	nameRE := regexp.MustCompile(`(?m)^pkgname=(\([^)]*\)|\S+)`)
	got := map[string]string{}
	for _, b := range builds {
		src, err := os.ReadFile(b)
		if err != nil {
			t.Fatal(err)
		}
		base := ""
		if m := baseRE.FindSubmatch(src); m != nil {
			base = strings.Trim(string(m[1]), `"'`)
		}
		m := nameRE.FindSubmatch(src)
		if m == nil {
			t.Fatalf("%s: no pkgname", b)
		}
		for _, n := range strings.Fields(strings.Trim(string(m[1]), "()")) {
			n = strings.ReplaceAll(strings.Trim(n, `"'`), "$pkgbase", base)
			got[n] = filepath.ToSlash(strings.TrimPrefix(filepath.Dir(b), r+"/"))
		}
	}
	for n, d := range got {
		if PublicPackages[n] != d {
			t.Errorf("%s (built by %s) is not in PublicPackages with that directory", n, d)
		}
	}
	for n := range PublicPackages {
		if _, ok := got[n]; !ok {
			t.Errorf("PublicPackages lists %s, which no PKGBUILD builds", n)
		}
	}
}

// --- the image trusts the key and names the repository ------------------------------------------

func TestImageTrustsReleaseKey(t *testing.T) {
	r := root(t)
	fpr, keyFile, err := resolveKey(r, "", "")
	if err != nil {
		t.Fatal(err)
	}
	shipped, err := os.ReadFile(keyFile)
	if err != nil {
		t.Fatalf("the release public key must be in the tree (base/keys/owner/<fpr>.asc): %v", err)
	}
	kr := filepath.Join(r, "iso-profiles/river/root-overlay/usr/share/pacman/keyrings")
	img, err := os.ReadFile(filepath.Join(kr, "runink.gpg"))
	if err != nil || !bytes.Equal(img, shipped) {
		t.Fatalf("the image's pacman keyring runink.gpg must be byte-identical to %s (err %v)", keyFile, err)
	}
	if _, err := keyringFromArmor(keyFile); err != nil {
		t.Fatal(err)
	}
	trusted, err := os.ReadFile(filepath.Join(kr, "runink-trusted"))
	if err != nil || !regexp.MustCompile(`(?m)^`+fpr+`:4:$`).Match(trusted) {
		t.Fatalf("runink-trusted must trust %s (err %v):\n%s", fpr, err, trusted)
	}
	for _, f := range []string{"KEYS", "install.sh"} {
		b, err := os.ReadFile(filepath.Join(r, f))
		if err != nil || !bytes.Contains(b, []byte(fpr)) {
			t.Errorf("%s does not carry the fingerprint %s", f, fpr)
		}
	}
	ml, err := os.ReadFile(filepath.Join(r, "iso-profiles/river/root-overlay/etc/pacman.d/mirrorlist-runink"))
	if err != nil {
		t.Fatal(err)
	}
	var servers []string
	for _, l := range strings.Split(string(ml), "\n") {
		if strings.HasPrefix(l, "Server = ") {
			servers = append(servers, strings.TrimPrefix(l, "Server = "))
		}
	}
	want := []string{"https://github.com/org-runink/river/releases/download/" + ReleaseTag, "https://runink.org/river/repo/x86_64"}
	if !slices.Equal(servers, want) {
		t.Fatalf("mirrorlist-runink servers %v, want %v", servers, want)
	}
}

// The installer step adds [runink] with the signature policy, reading the shipped files, and
// both copies of it say so (river lint installer-sync keeps them byte-identical).
func TestInstallerWritesRuninkStanza(t *testing.T) {
	r := root(t)
	for _, f := range []string{"installer/lib/35-pacman-keyring.sh", "iso-profiles/river/root-overlay/usr/local/lib/runink-install/35-pacman-keyring.sh"} {
		b, err := os.ReadFile(filepath.Join(r, f))
		if err != nil {
			t.Fatal(err)
		}
		for _, want := range []string{
			`[runink]\nSigLevel = Required DatabaseRequired\nInclude = \/etc\/pacman.d\/mirrorlist-runink`,
			"pacman-key --populate runink",
			"file:", // the leak guard
		} {
			if !bytes.Contains(b, []byte(want)) {
				t.Errorf("%s: missing %q", f, want)
			}
		}
	}
	// The build-time repository is file:// and TrustAll; it lives in the build config only.
	b, err := os.ReadFile(filepath.Join(r, "pacman/pacman.conf.in"))
	if err != nil || !bytes.Contains(b, []byte("Server = file://@LOCALREPO@")) {
		t.Fatalf("pacman/pacman.conf.in no longer has the build-time file:// [runink] (err %v)", err)
	}
	if _, err := os.Stat(filepath.Join(r, "iso-profiles/river/root-overlay/etc/pacman.conf")); err == nil {
		t.Fatal("the profile must not ship its own /etc/pacman.conf: the installer adds [runink] to the distribution's")
	}
}

// --- assemble ------------------------------------------------------------------------------

func TestAssembleRefusesPrivateDirectories(t *testing.T) {
	for _, name := range []string{"localrepo-server-private", "localrepo-runink-server", "Private"} {
		from := filepath.Join(t.TempDir(), name)
		if err := os.MkdirAll(from, 0o755); err != nil {
			t.Fatal(err)
		}
		err := Assemble(context.Background(), from, filepath.Join(t.TempDir(), "out"), io.Discard)
		if err == nil || !strings.Contains(err.Error(), "private build") {
			t.Fatalf("%s: want a refusal, got %v", name, err)
		}
	}
}

func TestAssembleRefusesNonEmptyOut(t *testing.T) {
	out := t.TempDir()
	if err := os.WriteFile(filepath.Join(out, "old.pkg.tar.zst"), nil, 0o644); err != nil {
		t.Fatal(err)
	}
	err := Assemble(context.Background(), t.TempDir(), out, io.Discard)
	if err == nil || !strings.Contains(err.Error(), "not empty") {
		t.Fatalf("got %v", err)
	}
}

// One package that is not public refuses the whole set, and nothing is written.
func TestAssembleRefusesTheWholeSet(t *testing.T) {
	needTools(t, "zstd", "repo-add")
	from := t.TempDir()
	tayga.write(t, from)
	baseRuntime.write(t, from)
	bad := baseCore
	bad.files = map[string]string{"usr/local/share/runink/core/deploy": "#!/bin/sh\n"}
	bad.write(t, from)
	fakePkg{name: "acme-console", ver: "1-1", arch: "x86_64"}.write(t, from)
	out := filepath.Join(t.TempDir(), "repo")
	err := Assemble(context.Background(), from, out, io.Discard)
	if err == nil {
		t.Fatal("assembled a set with a payload-carrying runink-core")
	}
	for _, want := range []string{"runink-core-2026.07-1-x86_64.pkg.tar.zst: carries 1 downstream payload file", "acme-console-1-1-x86_64.pkg.tar.zst: package \"acme-console\" is not one River builds"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("refusal lacks %q:\n%v", want, err)
		}
	}
	if _, err := os.Stat(out); err == nil {
		t.Fatal("a refused assemble wrote its output directory")
	}
}

func TestAssembleEndToEnd(t *testing.T) {
	needTools(t, "zstd", "repo-add")
	from := t.TempDir()
	for _, p := range []fakePkg{baseCore, baseRuntime, tayga} {
		p.write(t, from)
	}
	out := filepath.Join(t.TempDir(), "repo")
	var log bytes.Buffer
	if err := Assemble(context.Background(), from, out, &log); err != nil {
		t.Fatalf("%v\n%s", err, log.String())
	}
	if l, err := os.Readlink(filepath.Join(out, "runink.db")); err != nil || l != dbFile {
		t.Fatalf("runink.db -> %q (%v)", l, err)
	}
	sums, _ := os.ReadFile(filepath.Join(out, "SHA256SUMS"))
	for _, n := range []string{baseCore.fileName(), baseRuntime.fileName(), tayga.fileName(), dbFile, filesFile} {
		if !regexp.MustCompile(`(?m)^[0-9a-f]{64}  ` + regexp.QuoteMeta(n) + `$`).Match(sums) {
			t.Errorf("SHA256SUMS lacks %s:\n%s", n, sums)
		}
	}
	names, _ := os.ReadDir(out)
	for _, e := range names {
		if strings.HasSuffix(e.Name(), ".sig") {
			t.Fatalf("assemble must never sign: %s", e.Name())
		}
	}
	// The database names exactly the packages.
	if probs := checkDB(context.Background(), out, []string{baseCore.fileName(), baseRuntime.fileName(), tayga.fileName()}); len(probs) > 0 {
		t.Fatalf("db: %v", probs)
	}
}

// --- verify --------------------------------------------------------------------------------

func TestCheckStatus(t *testing.T) {
	const fpr = "95C0A7B97D547413E42660DDB06FE75626F15BF3"
	good := "[GNUPG:] NEWSIG\n[GNUPG:] GOODSIG B06FE75626F15BF3 x\n[GNUPG:] VALIDSIG AAAA 2026-09-28 1790000000 0 4 0 19 10 00 " + fpr + "\n"
	other := strings.Replace(good, " "+fpr, " 0D42EE6F7BEB734CD6DE7A3182CF96451FF6D40C", 1)
	cases := [][2]string{
		{good, ""},
		{other, "not " + fpr},
		{"[GNUPG:] BADSIG B06FE75626F15BF3 x\n", "BADSIG"},
		{"[GNUPG:] ERRSIG B06FE75626F15BF3 19 10 00 1790000000 9 -\n", "ERRSIG"},
		{good + "[GNUPG:] EXPKEYSIG B06FE75626F15BF3 x\n", "EXPKEYSIG"},
		{good + "[GNUPG:] REVKEYSIG B06FE75626F15BF3 x\n", "REVKEYSIG"},
		{"", "no VALIDSIG"},
	}
	for _, c := range cases {
		status, want := c[0], c[1]
		got := checkStatus(status, fpr)
		if (want == "") != (got == "") || !strings.Contains(got, want) {
			t.Errorf("status %q: got %q, want %q", status, got, want)
		}
	}
}

func TestKeyringFromArmor(t *testing.T) {
	dir := t.TempDir()
	f := filepath.Join(dir, "k.asc")
	body := "-----BEGIN PGP PUBLIC KEY BLOCK-----\nComment: test\n\naGVsbG8g\nd29ybGQ=\n=abcd\n-----END PGP PUBLIC KEY BLOCK-----\n"
	if err := os.WriteFile(f, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	b, err := keyringFromArmor(f)
	if err != nil || string(b) != "hello world" {
		t.Fatalf("got %q, %v", b, err)
	}
	if err := os.WriteFile(f, []byte("not a key"), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := keyringFromArmor(f); err == nil {
		t.Fatal("accepted a file with no armor")
	}
}

// Verify fails closed on an unsigned repository, wherever it runs (with or without its tools).
func TestVerifyFailsClosedUnsigned(t *testing.T) {
	dir := t.TempDir()
	for _, n := range []string{tayga.fileName(), dbFile, filesFile, "SHA256SUMS"} {
		if err := os.WriteFile(filepath.Join(dir, n), []byte("x"), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	err := Verify(context.Background(), dir, "95C0A7B97D547413E42660DDB06FE75626F15BF3", filepath.Join(dir, "none.asc"), io.Discard)
	if err == nil {
		t.Fatal("verified an unsigned repository")
	}
}

// testKey makes a throwaway signing key in a private GNUPGHOME (never the release key) and
// returns a signer and the armored public key file.
func testKey(t *testing.T, uid string) (fpr, asc string, sign func(file string)) {
	t.Helper()
	home, err := os.MkdirTemp("", "rrk")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(home, 0o700); err != nil {
		t.Fatal(err)
	}
	env := append(os.Environ(), "GNUPGHOME="+home)
	t.Cleanup(func() {
		c := exec.Command("gpgconf", "--kill", "all")
		c.Env = env
		_ = c.Run()
		os.RemoveAll(home)
	})
	run := func(args ...string) []byte {
		c := exec.Command("gpg", append([]string{"--batch", "--yes", "--quiet"}, args...)...)
		c.Env = env
		out, err := c.Output()
		if err != nil {
			t.Fatalf("gpg %v: %v", args, err)
		}
		return out
	}
	run("--passphrase", "", "--quick-gen-key", uid, "ed25519", "sign", "never")
	for _, l := range strings.Split(string(run("--with-colons", "--list-keys")), "\n") {
		if f := strings.Split(l, ":"); f[0] == "fpr" {
			fpr = f[9]
			break
		}
	}
	asc = filepath.Join(home, "pub.asc")
	if err := os.WriteFile(asc, run("--armor", "--export", fpr), 0o644); err != nil {
		t.Fatal(err)
	}
	return fpr, asc, func(file string) { run("--local-user", fpr, "--detach-sign", "--output", file+".sig", file) }
}

// signedRepo builds a small repository (packages, a database repo-add would write, SHA256SUMS)
// and signs every file the way base/river-sign does.
func signedRepo(t *testing.T, sign func(string)) string {
	t.Helper()
	dir := t.TempDir()
	pkgs := []fakePkg{baseCore, tayga}
	var db bytes.Buffer
	tw := tar.NewWriter(&db)
	for _, p := range pkgs {
		p.write(t, dir)
		desc := fmt.Sprintf("%%FILENAME%%\n%s\n\n%%NAME%%\n%s\n", p.fileName(), p.name)
		_ = tw.WriteHeader(&tar.Header{Name: p.name + "-" + p.ver + "/desc", Mode: 0o644, Size: int64(len(desc)), Typeflag: tar.TypeReg})
		_, _ = io.WriteString(tw, desc)
	}
	_ = tw.Close()
	writeZst(t, filepath.Join(dir, dbFile), db.Bytes())
	writeZst(t, filepath.Join(dir, filesFile), db.Bytes())
	for _, l := range []string{"db", "files"} {
		if err := os.Symlink(RepoName+"."+l+".tar.zst", filepath.Join(dir, RepoName+"."+l)); err != nil {
			t.Fatal(err)
		}
	}
	names := []string{dbFile, filesFile}
	for _, p := range pkgs {
		names = append(names, p.fileName())
	}
	if err := writeSums(dir, names); err != nil {
		t.Fatal(err)
	}
	for _, n := range append(names, "SHA256SUMS") {
		sign(filepath.Join(dir, n))
	}
	for _, l := range []string{"db", "files"} {
		if err := os.Symlink(RepoName+"."+l+".tar.zst.sig", filepath.Join(dir, RepoName+"."+l+".sig")); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

func TestVerifyEndToEnd(t *testing.T) {
	needTools(t, "gpg", "gpgv", "gpgconf", "zstd")
	fpr, asc, sign := testKey(t, "River repo test <test@example.invalid>")
	ctx := context.Background()

	dir := signedRepo(t, sign)
	if err := Verify(ctx, dir, fpr, asc, io.Discard); err != nil {
		t.Fatalf("a correctly signed repository failed: %v", err)
	}

	mustFail := func(name, want string, mutate func(dir string)) {
		t.Run(name, func(t *testing.T) {
			d := signedRepo(t, sign)
			mutate(d)
			err := Verify(ctx, d, fpr, asc, io.Discard)
			if err == nil || !strings.Contains(err.Error(), want) {
				t.Fatalf("want a failure containing %q, got %v", want, err)
			}
		})
	}
	mustFail("a package without its signature", "no signature", func(d string) {
		os.Remove(filepath.Join(d, tayga.fileName()+".sig"))
	})
	mustFail("the database without its signature", "runink.db: no signature", func(d string) {
		os.Remove(filepath.Join(d, "runink.db.sig"))
	})
	mustFail("a package changed after signing", "does not verify", func(d string) {
		p := filepath.Join(d, tayga.fileName())
		b, _ := os.ReadFile(p)
		os.WriteFile(p, append(b, 0), 0o644)
	})
	mustFail("a stray file", "not a repository file", func(d string) {
		os.WriteFile(filepath.Join(d, "notes.txt"), nil, 0o644)
	})
	mustFail("a package the database does not name", "not in runink.db", func(d string) {
		p := fakePkg{name: "runink-zfs", ver: "2.4.4-3", arch: "x86_64"}
		f := p.write(t, d)
		sign(f)
	})
	mustFail("the wrong key", "does not verify", func(d string) {
		_, _, other := testKey(t, "Someone else <else@example.invalid>")
		other(filepath.Join(d, tayga.fileName()))
	})
	// Right key file, wrong expected fingerprint: fails closed.
	if err := Verify(ctx, dir, "95C0A7B97D547413E42660DDB06FE75626F15BF3", asc, io.Discard); err == nil {
		t.Fatal("verified against a fingerprint that did not sign")
	}
}

// --- publish -------------------------------------------------------------------------------

func TestPublishRefusesUnverified(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, tayga.fileName()), []byte("x"), 0o644); err != nil {
		t.Fatal(err)
	}
	pages := filepath.Join(t.TempDir(), "pages")
	called := false
	defer func(old func(context.Context, ...string) ([]byte, error)) { gh = old }(gh)
	gh = func(context.Context, ...string) ([]byte, error) { called = true; return nil, nil }
	err := Publish(context.Background(), PublishOptions{Dir: dir, KeyFpr: "95C0A7B97D547413E42660DDB06FE75626F15BF3",
		KeyFile: filepath.Join(dir, "k.asc"), GitHub: true, PagesOut: pages}, io.Discard)
	if err == nil || called {
		t.Fatalf("published an unverified repository (err %v, gh called %v)", err, called)
	}
	if _, err := os.Stat(pages); err == nil {
		t.Fatal("wrote the Pages mirror for an unverified repository")
	}
}

func TestPublishRefusesPrivateDir(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "state-private")
	if err := os.Mkdir(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	err := Publish(context.Background(), PublishOptions{Dir: dir, PagesOut: t.TempDir()}, io.Discard)
	if err == nil || !strings.Contains(err.Error(), "private build") {
		t.Fatalf("got %v", err)
	}
}

// fileRepo is a repository directory by name and size alone, for the upload and mirror logic.
func fileRepo(t *testing.T, sizes map[string]int) (string, []repoFile, []*Package) {
	t.Helper()
	dir := t.TempDir()
	var pkgs []*Package
	for n, s := range sizes {
		if err := os.WriteFile(filepath.Join(dir, n), bytes.Repeat([]byte{1}, s), 0o644); err != nil {
			t.Fatal(err)
		}
		if strings.HasSuffix(n, pkgSuffix) {
			pkgs = append(pkgs, &Package{File: n, Size: int64(s)})
		}
	}
	files, err := repoFiles(dir)
	if err != nil {
		t.Fatal(err)
	}
	return dir, files, pkgs
}

var smallRepo = map[string]int{
	"linux-runink-7.2.7.zen1-1-x86_64.pkg.tar.zst": 3000, "linux-runink-7.2.7.zen1-1-x86_64.pkg.tar.zst.sig": 10,
	"runink-tayga-0.9.2-1-x86_64.pkg.tar.zst": 500, "runink-tayga-0.9.2-1-x86_64.pkg.tar.zst.sig": 10,
	"runink.db": 50, "runink.db.sig": 10, "runink.files": 60, "runink.files.sig": 10,
	"SHA256SUMS": 20, "SHA256SUMS.sig": 10,
}

func TestWritePagesSplitsBySize(t *testing.T) {
	dir, files, pkgs := fileRepo(t, smallRepo)
	out := filepath.Join(t.TempDir(), "static/river/repo/x86_64")
	var log bytes.Buffer
	if err := writePages(dir, out, files, pkgs, 1000, &log); err != nil {
		t.Fatal(err)
	}
	got, _ := os.ReadDir(out)
	var names []string
	for _, e := range got {
		names = append(names, e.Name())
		if !e.Type().IsRegular() {
			t.Errorf("%s is not a regular file", e.Name())
		}
	}
	want := []string{"SHA256SUMS", "SHA256SUMS.sig", "runink-tayga-0.9.2-1-x86_64.pkg.tar.zst", "runink-tayga-0.9.2-1-x86_64.pkg.tar.zst.sig",
		"runink.db", "runink.db.sig", "runink.files", "runink.files.sig"}
	if !slices.Equal(names, want) {
		t.Fatalf("mirror holds %v, want %v", names, want)
	}
	if !strings.Contains(log.String(), "NOT mirrored, over the Pages limit (GitHub release only): linux-runink") {
		t.Fatalf("the omission must be reported:\n%s", log.String())
	}

	// A second publish removes what the repository no longer has and keeps nothing stale.
	stale := filepath.Join(out, "runink-tayga-0.9.1-1-x86_64.pkg.tar.zst")
	if err := os.WriteFile(stale, nil, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := writePages(dir, out, files, pkgs, 1000, io.Discard); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(stale); err == nil {
		t.Fatal("a superseded package stayed on the mirror")
	}

	// Anything that is not a repository file means --pages-out points at the wrong directory.
	if err := os.WriteFile(filepath.Join(out, "index.html"), nil, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := writePages(dir, out, files, pkgs, 1000, io.Discard); err == nil || !strings.Contains(err.Error(), "index.html") {
		t.Fatalf("got %v", err)
	}
}

func TestWritePagesRefusesOversizeDatabase(t *testing.T) {
	dir, files, pkgs := fileRepo(t, map[string]int{"runink.db": 2000, "runink-tayga-0.9.2-1-x86_64.pkg.tar.zst": 10})
	if err := writePages(dir, filepath.Join(t.TempDir(), "o"), files, pkgs, 1000, io.Discard); err == nil {
		t.Fatal("a database over the limit cannot be left off the mirror")
	}
}

type ghCall []string

func fakeGH(t *testing.T, view string, viewErr error) *[]ghCall {
	t.Helper()
	var calls []ghCall
	old := gh
	t.Cleanup(func() { gh = old })
	gh = func(_ context.Context, args ...string) ([]byte, error) {
		calls = append(calls, args)
		if args[1] == "view" {
			return []byte(view), viewErr
		}
		return nil, nil
	}
	return &calls
}

func TestPublishGitHubCreatesPrerelease(t *testing.T) {
	dir, files, _ := fileRepo(t, smallRepo)
	calls := fakeGH(t, "", fmt.Errorf("stage 1 (gh release view): exit status 1: release not found"))
	o := PublishOptions{GitHubRepo: GitHubRepo, Tag: ReleaseTag, Prune: true}
	if err := publishGitHub(context.Background(), o, dir, files, io.Discard); err != nil {
		t.Fatal(err)
	}
	create := strings.Join((*calls)[1], " ")
	for _, want := range []string{"release create " + ReleaseTag, "--prerelease", "--latest=false", "-R " + GitHubRepo} {
		if !strings.Contains(create, want) {
			t.Errorf("create %q lacks %q", create, want)
		}
	}
	// Packages go up first, the database last.
	up1, up2 := strings.Join((*calls)[2], " "), strings.Join((*calls)[3], " ")
	if !strings.Contains(up1, "upload "+ReleaseTag+" --clobber") || strings.Contains(up1, "runink.db") || !strings.Contains(up1, "runink-tayga") {
		t.Errorf("first upload must be the packages only: %s", up1)
	}
	if !strings.Contains(up2, "runink.db") || strings.Contains(up2, pkgSuffix+" ") {
		t.Errorf("second upload must be the database: %s", up2)
	}
	if len(*calls) != 4 {
		t.Errorf("a new release has nothing to prune; calls: %v", *calls)
	}
}

func TestPublishGitHubPrunesAfterUpload(t *testing.T) {
	dir, files, _ := fileRepo(t, smallRepo)
	view := `{"isPrerelease":true,"isDraft":false,"assets":[{"name":"runink.db"},{"name":"runink-tayga-0.9.1-1-x86_64.pkg.tar.zst"}]}`
	calls := fakeGH(t, view, nil)
	if err := publishGitHub(context.Background(), PublishOptions{GitHubRepo: GitHubRepo, Tag: ReleaseTag, Prune: true}, dir, files, io.Discard); err != nil {
		t.Fatal(err)
	}
	last := strings.Join((*calls)[len(*calls)-1], " ")
	if !strings.Contains(last, "delete-asset "+ReleaseTag+" runink-tayga-0.9.1-1-x86_64.pkg.tar.zst --yes") {
		t.Fatalf("the superseded asset is deleted last: %v", *calls)
	}
}

func TestPublishGitHubRefusesNonPrerelease(t *testing.T) {
	dir, files, _ := fileRepo(t, smallRepo)
	calls := fakeGH(t, `{"isPrerelease":false,"isDraft":false,"assets":[]}`, nil)
	err := publishGitHub(context.Background(), PublishOptions{GitHubRepo: GitHubRepo, Tag: ReleaseTag}, dir, files, io.Discard)
	if err == nil || len(*calls) != 1 {
		t.Fatalf("uploaded to a release that could become latest (err %v, calls %v)", err, *calls)
	}
}
