// SPDX-FileCopyrightText: 2026 The RIVER Authors
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"bytes"
	"encoding/base64"
	"fmt"
	"image"
	"image/color"
	"image/jpeg"
	"image/png"
	"math"
	"strings"
)

// All fixtures are generated here, deterministically, from code: no third-party pixels,
// no downloaded text, nothing to license. The generated bytes are also written to the
// evidence dir by the checks that use them, so a verdict can be reproduced by hand.

type box struct{ X1, Y1, X2, Y2 float64 }

func (b box) area() float64 { return math.Max(0, b.X2-b.X1) * math.Max(0, b.Y2-b.Y1) }

func iou(a, b box) float64 {
	in := box{math.Max(a.X1, b.X1), math.Max(a.Y1, b.Y1), math.Min(a.X2, b.X2), math.Min(a.Y2, b.Y2)}
	i := in.area()
	if in.X2 <= in.X1 || in.Y2 <= in.Y1 {
		i = 0
	}
	u := a.area() + b.area() - i
	if u <= 0 {
		return 0
	}
	return i / u
}

// scene draws a w×h image: soft vertical gradient background, one filled shape of the
// given colour inside target, and (when distractor) a blue disc elsewhere.
func scene(w, h int, shape string, fill color.RGBA, target box, distractor bool) *image.RGBA {
	img := image.NewRGBA(image.Rect(0, 0, w, h))
	for y := 0; y < h; y++ {
		g := uint8(225 - 40*y/h)
		for x := 0; x < w; x++ {
			img.SetRGBA(x, y, color.RGBA{g, g, uint8(int(g) - 10), 255})
		}
	}
	// A dark "floor line" so the frame is not a pure gradient.
	for y := h * 7 / 10; y < h*7/10+3; y++ {
		for x := 0; x < w; x++ {
			img.SetRGBA(x, y, color.RGBA{90, 90, 90, 255})
		}
	}
	if distractor {
		cx, cy, r := float64(w)*0.16, float64(h)*0.22, float64(h)*0.11
		disc(img, cx, cy, r, color.RGBA{30, 60, 200, 255})
	}
	switch shape {
	case "rect":
		for y := int(target.Y1); y < int(target.Y2); y++ {
			for x := int(target.X1); x < int(target.X2); x++ {
				img.SetRGBA(x, y, fill)
			}
		}
	case "disc":
		disc(img, (target.X1+target.X2)/2, (target.Y1+target.Y2)/2, (target.X2-target.X1)/2, fill)
	}
	return img
}

func disc(img *image.RGBA, cx, cy, r float64, c color.RGBA) {
	for y := int(cy - r); y <= int(cy+r); y++ {
		for x := int(cx - r); x <= int(cx+r); x++ {
			if (float64(x)-cx)*(float64(x)-cx)+(float64(y)-cy)*(float64(y)-cy) <= r*r {
				img.SetRGBA(x, y, c)
			}
		}
	}
}

func encJPEG(img image.Image) []byte {
	var b bytes.Buffer
	_ = jpeg.Encode(&b, img, &jpeg.Options{Quality: 85})
	return b.Bytes()
}

func encPNG(img image.Image) []byte {
	var b bytes.Buffer
	_ = (&png.Encoder{CompressionLevel: png.BestCompression}).Encode(&b, img)
	return b.Bytes()
}

func dataURI(mime string, b []byte) string {
	return "data:" + mime + ";base64," + base64.StdEncoding.EncodeToString(b)
}

// Vision fixture geometry. 1024×576 (max edge 1024, 16:9 like a camera frame, both sides
// multiples of 32 so Qwen-VL's smart-resize is the identity). The red box sits low and
// right, so its pixel box and its 0-1000-normalised box differ by hundreds on the y axis:
// a normalised answer cannot score IoU ≥ 0.5 against the pixel truth by accident.
var (
	visW, visH = 1024, 576
	redTruth   = box{640, 300, 880, 480}
)

// ── Long-context haystack ─────────────────────────────────────────────────────────────

var (
	hsCities = []string{"Lisbon", "Porto", "Montreal", "Lyon", "Valencia", "Recife", "Toronto", "Quebec",
		"Bilbao", "Curitiba", "Marseille", "Seville", "Halifax", "Nantes", "Braga", "Rosario"}
	hsGoods = []string{"copper wire", "oat flour", "solar panels", "bicycle frames", "olive oil",
		"ceramic tiles", "wool blankets", "lithium cells", "coffee beans", "steel bolts", "paper rolls"}
	hsVerbs = []string{"received", "dispatched", "inspected", "rejected", "re-labelled", "counted"}
)

// haystack returns filler logistics records of roughly nChars characters, with needle
// inserted at the given depth (0..1). Records are pseudo-random but deterministic (LCG),
// so every model sees byte-identical prompts.
func haystack(nChars int, needle string, depth float64) string {
	var b strings.Builder
	seed := uint32(20260924)
	next := func(n int) int { seed = seed*1664525 + 1013904223; return int(seed>>8) % n }
	inserted := false
	for i := 0; b.Len() < nChars; i++ {
		if !inserted && float64(b.Len()) >= depth*float64(nChars) {
			b.WriteString(needle + "\n")
			inserted = true
		}
		fmt.Fprintf(&b, "Record %05d: the %s depot %s %d crates of %s on day %d; supervisor badge %04d.\n",
			i, hsCities[next(len(hsCities))], hsVerbs[next(len(hsVerbs))], 3+next(400),
			hsGoods[next(len(hsGoods))], 1+next(365), next(10000))
	}
	if !inserted {
		b.WriteString(needle + "\n")
	}
	return b.String()
}

const (
	needleText   = "IMPORTANT NOTE: the maintenance passphrase for the River node is AMBER-FALCON-4417."
	needleAnswer = "AMBER-FALCON-4417"
)
